[project]
name = "seetapsych-face-hub"
description = "Face modules for SeetaPsych"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]
license = { file = "LICENSE" }
dependencies = [
    "seetapsych-lib",
]

[project.urls]
Homepage = "https://github.com/seetapsych/seetapsych-face-hub"
Repository = "https://github.com/seetapsych/seetapsych-face-hub"
Issues = "https://github.com/seetapsych/seetapsych-face-hub/issues"

[project.optional-dependencies]
all = [
    "mediapipe>=0.10.33",
    "numpy>=2.2.6",
    "onnx>=1.20.1",
    "onnxruntime>=1.24; sys_platform == 'darwin' and python_version > '3.10'",
    "onnxruntime<1.24; sys_platform == 'darwin' and python_version <= '3.10'",
    "onnxruntime-gpu>=1.24; sys_platform != 'darwin' and python_version > '3.10'",
    "onnxruntime-gpu<1.24; sys_platform != 'darwin' and python_version <= '3.10'",
    "opencv-python>=4.11.0.86",
    "safetensors>=0.7.0",
    "scikit-image>=0.25.2",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
]
dev = [
    "seetapsych-face-hub[all]",
    "build>=1.4.4",
    "twine>=6.2.0",
]

[dependency-groups]
dev = [
    "seetapsych-face-hub[dev]",
]

[tool.uv]
default-groups = ["dev"]

[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.0.dev0"
tag-pattern = "^r(?P<version>[^-]+)$"

[tool.hatch.build.hooks.vcs]
version-file = "seetapsych_face_hub/_version.py"

[build-system]
requires = ["hatchling>=1.26", "hatch-vcs>=0.4.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["seetapsych_face_hub"]

[tool.hatch.build.targets.wheel.package-data]
seetapsych_face_hub = ["modules/**/*.yml"]

[tool.uv.sources]
# seetapsych-lib = { workspace = true }

torch = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or (sys_platform == 'win32' and platform_machine == 'AMD64')" },
    { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
]

torchvision = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or (sys_platform == 'win32' and platform_machine == 'AMD64')" },
    { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
]

torchaudio = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or (sys_platform == 'win32' and platform_machine == 'AMD64')" },
    { index = "pytorch-cpu", marker = "sys_platform == 'darwin'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
